# Generated by Django 5.0.6 on 2024-06-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productepisode_product_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='customers', to='store.product'),
        ),
    ]
